yarnPath: .yarn/releases/yarn-4.1.1.cjs
nodeLinker: pnp
supportedArchitectures: {
    os: ['current', 'linux'],
    # 지금 생각해보면 윈도우도 x64아닌가...?
    cpu: ['current', 'x64'],
    libc: ['current', 'glibc', 'musl'],
  }
